#include "stdafx.h"
// this file is autogenerated. do not edit.

#include "appplex-conf.hpp"
#include "unit.hpp"
#include "public\cmd\unit-cmd.hpp"

void app_units_setup::create_units(shared_ptr<unit_list> ul0)
{
	ul = ul0;

#ifdef UNIT_CMD
	add_unit(unit_cmd::new_instance(), true);
#endif

}
