// this file is autogenerated. do not edit.

#include "pfm-def.h"


// #define UNIT_COMMENT
// #define UNIT_CMD
// #define UNIT_TEMPLATE
// #define UNIT_TEST_FFMPEG
// #define UNIT_TEST_VPLAYER_ANDROID
// #define UNIT_TEST_VPLAYER_IOS
// #define UNIT_TEST_GL

#if defined PLATFORM_WINDOWS_PC || defined PLATFORM_ANDROID
	#define UNIT_GL_FRAG_SHADER_DEMO
#endif

// #define UNIT_MX_LISP
// #define UNIT_TEST_SHADOW_MAP
// #define UNIT_TEST_KUBE_SPHERE
// #define UNIT_TEST_GRID
// #define UNIT_TEST_REFLECTIONS
// #define UNIT_TEST_DYN_GEOMETRY
// #define UNIT_TEST_FREETYPE_GL
// #define UNIT_TEST_NORMAL_MAPPING
// #define UNIT_KEMX
// #define UNIT_KINETIC_SCROLLING
// #define UNIT_ABSTRACT_RACING
// #define UNIT_TEST_FMOD
// #define UNIT_UX_TEST
// #define UNIT_TEXXED
// #define UNIT_EXERCISE
// #define UNIT_GEN_TEXTURE
// #define UNIT_TEST
// #define UNIT_TEST_FREEIMAGE
// #define UNIT_TEST_OPENVG
// #define UNIT_TEST_STK
// #define UNIT_TEST_AUDIOENGINE
// #define UNIT_TEST_SND_ANDROID
// #define UNIT_TEST_SND_GENERATORS
// #define UNIT_COMMENT
// #define UNIT_BARNES_HUT
// #define UNIT_KAPPAXX
// #define UNIT_RELIQUUS
// #define UNIT_ORBITAL_DEATHMATCH
// #define UNIT_SHIPWRECKED
// #define UNIT_VOROFRACT
// #define UNIT_MUSIX
// #define UNIT_BREAK_REMINDER
// #define UNIT_TEST_DIGITAL_KRIKITS
// #define UNIT_METROLIFE


#define MOD_BOOST
#define MOD_SND
#define MOD_GFX
#define MOD_STK

#define SINGLE_UNIT_BUILD

