#include "stdafx.h"
// this file is autogenerated. do not edit.

#include "appplex-conf.hpp"
#include "unit.hpp"
#include "public/gl-frag-shader-demo/unit-gl-frag-shader-demo.hpp"

void app_units_setup::create_units(shared_ptr<unit_list> ul0)
{
	ul = ul0;

#ifdef UNIT_GL_FRAG_SHADER_DEMO
	add_unit(unit_gl_frag_shader_demo::new_instance(), true);
#endif

}
