#include "stdafx.hxx"
// this file is autogenerated. do not edit.

#include "appplex-conf.hxx"
#include "mws-mod.hxx"
#include "kxmdb/mod-kxmdb.hxx"


void mws_mod_setup::append_mod_list(mws_sp<mws_mod_list> i_mod_list)
{
	ul = i_mod_list;

#if MOD_KXMDB
	add_mod(mod_kxmdb::nwi(), "src/mod/prv/kxmdb/", true);
#endif

}
