#include "stdafx.hxx"
// this file is autogenerated. do not edit.

#include "appplex-conf.hxx"
#include "mws-mod.hxx"
#include "net/ws-client-server-async/mod-ws-client-server-async.hxx"


void mws_mod_setup::append_mod_list(mws_sp<mws_mod_list> i_mod_list)
{
	ul = i_mod_list;

#if MOD_WS_CLIENT_SERVER_ASYNC
	add_mod(mod_ws_client_server_async::nwi(), "src/mod/prv/net/ws-client-server-async/", true);
#endif

}
