// this file is autogenerated. do not edit.

#include "pfm-def.h"


// #define UNIT_PNG
// #define UNIT_JCV
// #define UNIT_CMD
// #define UNIT_GL_FRAG_SHADER_DEMO
#define UNIT_TEMPLATE
// #define UNIT_MX_LISP
// #define UNIT_KEMX
// #define UNIT_KINETIC_SCROLLING
// #define UNIT_ABSTRACT_RACING
// #define UNIT_TEXXED
// #define UNIT_EXERCISE
// #define UNIT_GEN_TEXTURE
// #define UNIT_GLOBAL_FLIGHT_PATHS
// #define UNIT_LAYERED_CAR_PAINT
// #define UNIT_TEST
// #define UNIT_TEST_FFMPEG
// #define UNIT_TEST_VPLAYER_ANDROID
// #define UNIT_TEST_VPLAYER_IOS
// #define UNIT_TEST_GL
// #define UNIT_TEST_SHADOW_MAP
// #define UNIT_TEST_KUBE_SPHERE
// #define UNIT_TEST_GRID
// #define UNIT_TEST_DYN_GEOMETRY
// #define UNIT_TEST_FREETYPE_GL
// #define UNIT_TEST_NORMAL_MAPPING
// #define UNIT_TEST_FMOD
// #define UNIT_TEST_MWS
// #define UNIT_TEST_FREEIMAGE
// #define UNIT_TEST_OPENVG
// #define UNIT_TEST_STK
// #define UNIT_TEST_AUDIOENGINE
// #define UNIT_TEST_SND_ANDROID
// #define UNIT_TEST_SND_GENERATORS
// #define UNIT_TEST_TRAIL
// #define UNIT_TEST_VIDEO_RECORDING
// #define UNIT_TEST_TOUCH_INPUT
// #define UNIT_TEST_GL_UNIFORM_BLOCKS
// #define UNIT_TEST_RES_LD
// #define UNIT_TEST_GL_OUTLINES
// #define UNIT_APPPLEXX_CONF
// #define UNIT_BARNES_HUT
// #define UNIT_KAPPAXX
// #define UNIT_RELIQUUS
// #define UNIT_ORBITAL_DEATHMATCH
// #define UNIT_SHIPWRECKED
// #define UNIT_VOROFRACT
// #define UNIT_MUSIX
// #define UNIT_OMNIRECALL
// #define UNIT_METROLIFE
// #define UNIT_TANGLED_MEMORIES
// #define UNIT_SPACETIME_SINKHOLE
// #define UNIT_VORONOI_KEYBOARD
// #define UNIT_KXMDB
// #define UNIT_TEST_DIGITAL_KRIKITS
// #define UNIT_TEST_JEWELRY
// #define UNIT_TECHNO_GLOBE
// #define UNIT_VIDEO_EDITOR
// #define UNIT_TEXT_EXTRACTOR


#define MOD_GFX
#define MOD_VECTOR_FONTS
#define MOD_FONTS
#define MOD_MWS
#define MOD_FORMAT
#define MOD_FREETYPE
#define MOD_FREETYPE_GL
#define MOD_PNG

#define SINGLE_UNIT_BUILD

