#include "stdafx.hxx"
// this file is autogenerated. do not edit.

#include "appplex-conf.hxx"
#include "unit.hxx"
#include "app/units/public/template/unit-template.hxx"

void app_units_setup::create_units(mws_sp<unit_list> i_unit_list)
{
	ul = i_unit_list;

#ifdef UNIT_TEMPLATE
	add_unit(unit_template::nwi(), "src/app/units/public/template", true);
#endif

}
